backend/src/analysis/urls.py
from django.urls import include, path
from rest_framework.routers import DefaultRouter

from .views import (
    AnalysisTakeDetailView,
    SignalAnalysisCreateView,
    SignalAnalysisDetailView,
    SignalAnalysisListView,
    SignalAnalysisModelViewSet,
    SignalAnalysisProcessingView,
    SignalAnalysisTableView,
    SignalTakesHistoryView,
    TakeProcessingView,
    TakeResultView,
    TakeTempView,
    create_analysis_take,
    csv_preview,
    TakeExisingView,
)

router = DefaultRouter()
router.register("analysis", SignalAnalysisModelViewSet, basename="analysis_")

urlpatterns = [
    path("api/v1/", include(router.urls)),
    path("", SignalAnalysisCreateView.as_view(), name="create_signal_analysis"),
    path("list/", SignalAnalysisListView.as_view(), name="create_signal_analysis"),
    path("table/", SignalAnalysisTableView.as_view(), name="create_signal_analysis"),
    path(
        "<int:pk>/", SignalAnalysisDetailView.as_view(), name="signal_analysis_detail"
    ),
    path(
        "take/<int:pk>/", AnalysisTakeDetailView.as_view(), name="analysis_take_detail"
    ),
    path(
        "take_new/<int:analysis_id>/<int:pk>/",
        TakeTempView.as_view(),
        name="analysis_take_new",
    ),
    path(
        "take_existing/<int:analysis_id>/<int:pk>/",
        TakeExisingView.as_view(),
        name="analysis_take_existing",
    ),
    path(
        "take/history/<int:pk>/",
        SignalTakesHistoryView.as_view(),
        name="analysis_take_history",
    ),
    path(
        "<int:analysis_id>/take/create/",
        create_analysis_take,
        name="create_analysis_take",
    ),
    path("csv-preview/<int:id>/", csv_preview, name="csv_preview"),
    path(
        "processing/<int:analysis_id>/",
        SignalAnalysisProcessingView.as_view(),
        name="analysis_processing",
    ),
    path(
        "<int:analysis_id>/take/processing/",
        TakeProcessingView.as_view(),
        name="take_processing",
    ),
    path("take/<int:pk>/result/", TakeResultView.as_view(), name="take_result"),
]

backend/src/backend/urls.py
from analysis import urls as analysis_urls
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic.base import RedirectView
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView
from rest_framework import routers
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

from .api import UserViewSet
from .views import Login, Logout, SignUp

router = routers.DefaultRouter()
router.register("users", UserViewSet, basename="api-users")

urlpatterns = [
    path(
        "api/schema/swagger-ui/",
        SpectacularSwaggerView.as_view(url_name="schema"),
    ),
    path("api/schema/", SpectacularAPIView.as_view(), name="schema"),
    path("api/", include(router.urls)),
    path("api/token/", TokenObtainPairView.as_view(), name="token_obtain_pair"),
    path("api/token/refresh/", TokenRefreshView.as_view(), name="token_refresh"),
    path("admin/", admin.site.urls),
    path("analysis/", include(analysis_urls)),
    path("accounts/login/", Login.as_view(), name="login"),
    path("logout/", Logout.as_view(), name="logout"),
    path("signup/", SignUp.as_view(), name="signup"),
    path("", RedirectView.as_view(url="analysis/", permanent=False), name="index"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

backend/src/analysis/models.py
from django.conf import settings
from django.db import models
from django.utils.translation import gettext_lazy as _
from django_fsm import FSMField, transition
from model_utils.models import TimeStampedModel
from processing.tasks import process_analysis


class SignalAnalysis(TimeStampedModel):
    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True
    )
    input_signal = models.FileField(blank=True, null=True)
    title = models.CharField(max_length=255, null=False, blank=False)
    description = models.TextField()
    signalSpectogram = models.ImageField(null=True)
    state = FSMField(default="new")

    class Meta:
        verbose_name = _("Signal Analysis")
        verbose_name_plural = _("Signal Analyses")

    @transition(field=state, source="new", target="in_progress")
    def start_processing(self):
        process_analysis(self.pk)

    @transition(field=state, source=["new", "in_progress"], target="processed")
    def finish_processing(self):
        pass


class AnalysisTake(TimeStampedModel):
    analysis = models.ForeignKey(SignalAnalysis, on_delete=models.CASCADE)

    comment = models.TextField(blank=True, null=True)
    analysis_result = models.JSONField(null=True, blank=True)
    window_size = models.PositiveIntegerField(default=1024)
    overlap = models.PositiveIntegerField(default=128)
    fs = models.PositiveIntegerField(default=48000)
    som_hitmap = models.ImageField(null=True)
    state = FSMField(default="new")

    class Meta:
        verbose_name = _("Analysis Take")
        verbose_name_plural = _("Analysis Takes")

    @transition(field=state, source="new", target="in_progress")
    def start_processing(self):
        pass

    @transition(field=state, source="in_progress", target="processed")
    def finish_processing(self):
        pass

    # FK to SignalAnalysis
    # Comment
    # input params
    # JSON result
    # graph images ...

backend/src/analysis/forms.py
from django import forms

from .models import AnalysisTake, SignalAnalysis


INPUT_TAILWIND_CLASS = "peer h-full w-full rounded-md border border-blue-gray-200 bg-transparent px-3 py-3 font-sans text-sm font-normal text-blue-gray-700 outline outline-0 transition-all placeholder-shown:border placeholder-shown:border-blue-gray-200 placeholder-shown:border-t-blue-gray-200 focus:border-2 focus:border-pink-500 focus:outline-0 disabled:border-0 disabled:bg-blue-gray-50"


class SignalAnalysisForm(forms.ModelForm):
    class Meta:
        model = SignalAnalysis
        fields = ["input_signal", "title", "description"]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Apply Tailwind CSS classes to each field
        self.fields["input_signal"].widget.attrs.update(
            {
                "class": "mt-1 block w-full text-sm text-gray-500 file:mr-4 file:py-2 file:px-4 file:rounded-full file:border-0 file:text-sm file:font-semibold file:bg-indigo-50 file:text-indigo-700 hover:file:bg-indigo-100"
            }
        )
        self.fields["title"].widget.attrs.update({"class": INPUT_TAILWIND_CLASS})
        self.fields["description"].widget.attrs.update({"class": INPUT_TAILWIND_CLASS})


class AnalysisTakeForm(forms.ModelForm):
    class Meta:
        model = AnalysisTake
        fields = ["analysis", "window_size", "overlap", "fs", "comment"]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        # Apply Tailwind CSS classes to each field
        self.fields["window_size"].widget.attrs.update({"class": INPUT_TAILWIND_CLASS})
        self.fields["overlap"].widget.attrs.update({"class": INPUT_TAILWIND_CLASS})
        self.fields["fs"].widget.attrs.update({"class": INPUT_TAILWIND_CLASS})
        self.fields["comment"].widget.attrs.update({"class": INPUT_TAILWIND_CLASS})

        # Set default values for the fields if not already provided
        self.fields["window_size"].initial = (
            self.fields["window_size"].initial or 1024
        )  # Replace 1024 with your default value
        self.fields["overlap"].initial = (
            self.fields["overlap"].initial or 128
        )  # Replace 512 with your default value
        self.fields["fs"].initial = (
            self.fields["fs"].initial or 48000
        )  # Replace 44100 with your default value

backend/src/analysis/views.py
import csv

from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from django.views.generic import TemplateView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView
from processing.tasks import process_analysis, process_take
from rest_framework import viewsets
from rest_framework.authentication import SessionAuthentication
from rest_framework.permissions import IsAuthenticatedOrReadOnly

from .forms import AnalysisTakeForm, SignalAnalysisForm
from .models import AnalysisTake, SignalAnalysis
from .serializers import SignalAnalysisSerializer


class SignalAnalysisModelViewSet(LoginRequiredMixin, viewsets.ModelViewSet):
    queryset = SignalAnalysis.objects.all()
    serializer_class = SignalAnalysisSerializer
    authentication_classes = [SessionAuthentication]
    permission_classes = [IsAuthenticatedOrReadOnly]

    def perform_create(self, serializer):
        serializer.save(created_by=self.request.user)


class SignalAnalysisCreateView(LoginRequiredMixin, CreateView):
    model = SignalAnalysis
    form_class = SignalAnalysisForm
    template_name = "signal_analysis_main.html"

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        response = super().form_valid(form)
        process_analysis(form.instance.pk)
        # form.instance.start_processing()
        # form.instance.save()
        return response

    def get_success_url(self):
        # Redirect to a detail view for the created object
        return reverse("analysis_processing", kwargs={"analysis_id": self.object.pk})


class SignalAnalysisDetailView(LoginRequiredMixin, DetailView):
    model = SignalAnalysis
    template_name = "signal_analysis_detail.html"


class AnalysisTakeCreateView(LoginRequiredMixin, CreateView):
    model = AnalysisTake
    form_class = AnalysisTakeForm
    template_name = "analysis_take_form.html"

    def form_valid(self, form):
        form.instance.analysis = self.kwargs.get("analysis_id")
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        """Insert the form into the context dict."""
        context = super().get_context_data(**kwargs)
        context["analysis"] = self.kwargs.get("analysis_id")
        return context

    def get_success_url(self):
        return reverse("analysis_take_detail", kwargs={"pk": self.object.pk})


def create_analysis_take(request, analysis_id):
    if request.method == "POST":
        form = AnalysisTakeForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(
                reverse(
                    "analysis_take_new",
                    kwargs={
                        "pk": form.instance.pk,
                        "analysis_id": form.instance.analysis.pk,
                    },
                )  # replace with take_new_section
            )
        return HttpResponse(f"{form.is_valid()} {form.errors}")
    form = AnalysisTakeForm()
    return render(
        request, "analysis_take_form.html", {"form": form, "analysis": analysis_id}
    )


class AnalysisTakeDetailView(LoginRequiredMixin, DetailView):
    model = AnalysisTake
    template_name = "analysis_take_detail.html"


def csv_preview(request, id):
    # Assuming you have a CSV file path or you can modify this to handle uploaded files
    signal = get_object_or_404(SignalAnalysis, pk=id)
    with open(signal.input_signal.name, "r", encoding="utf-8") as file:
        if signal.input_signal.name.split(".")[-1] == ".csv":
            csv_data = csv.reader(file)
        else:
            csv_data = file.read()
        # Convert csv data to list for easy processing in the template
        context = {
            "csv_data": list(csv_data),
        }
    return render(request, "preview_table.html", context)


class SignalAnalysisListView(LoginRequiredMixin, TemplateView):
    template_name = "signal_analysis_list.html"


class TakeTempView(LoginRequiredMixin, TemplateView):
    template_name = "take_new_section.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["take_id"] = kwargs.get("pk")
        context["analysis_id"] = kwargs.get("analysis_id")
        return context


class TakeExisingView(TakeTempView):
    template_name = "take_existing_section.html"


class SignalAnalysisTableView(LoginRequiredMixin, TemplateView):
    template_name = "signal_analysis_table.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["signal_analysis_list"] = SignalAnalysis.objects.filter(
            created_by=self.request.user
        ).order_by("-created")

        return context


class SignalTakesHistoryView(LoginRequiredMixin, TemplateView):
    template_name = "signal_takes_hisory.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        analysis_take_id = kwargs.get("pk")
        analysis_take = get_object_or_404(AnalysisTake, pk=analysis_take_id)
        context["takes"] = AnalysisTake.objects.filter(
            analysis__id=analysis_take.analysis.id
        ).order_by("-created")

        return context


class SignalAnalysisProcessingView(LoginRequiredMixin, TemplateView):
    template_name = "signal_analysis_processing.html"

    def get_context_data(self, **kwargs):
        """Insert the form into the context dict."""
        context = super().get_context_data(**kwargs)
        context["analysis"] = self.kwargs.get("analysis_id")
        return context


class TakeProcessingView(LoginRequiredMixin, TemplateView):
    template_name = "take_processing.html"

    def get_context_data(self, **kwargs):
        """Insert the form into the context dict."""
        context = super().get_context_data(**kwargs)
        analysis = self.kwargs.get("analysis_id")
        signal = get_object_or_404(SignalAnalysis, pk=analysis)
        take = signal.analysistake_set.last()
        if take.analysis_result is None:
            process_take(take.pk)
            context["processed"] = False
        context["processed"] = True
        context["take"] = take.id
        context["analysis_id"] = signal.id
        return context


class TakeResultView(LoginRequiredMixin, TemplateView):
    template_name = "analysis_take_result.html"

    def get_context_data(self, **kwargs):
        """Insert the form into the context dict."""
        context = super().get_context_data(**kwargs)
        pk = self.kwargs.get("pk")
        take = get_object_or_404(AnalysisTake, pk=pk)
        context["take"] = take
        results_color = "gray"
        if take.analysis_result is None:
            status = "in_progress"
            context["processed"] = False
            return context
        context["processed"] = True
        status = take.analysis_result.get("status")
        if status == "good":
            results_color = "green"
        elif status == "bad":
            results_color = "red"

        context["results_color"] = results_color
        context["results_status"] = status
        return context

backend/src/analysis/templates/analysis_take_detail.html
    <div class="bg-white p-4 shadow-md rounded" id="takeForm">
      <h2 class="text-lg font-semibold mb-4">Current Analysis Parameters</h2>
      <!-- Parameters form elements -->
      <div><label class="block mb-2 text-sm font-medium text-gray-700">Window Size</label>{{ object.window_size }}</div>

      <div> <label class="block mb-2 text-sm font-medium text-gray-700">Overlap</label>{{ object.overlap }}</div>

      <div><label class="block mb-2 text-sm font-medium text-gray-700">FS</label>{{ object.fs }}</div>
      <div><label class="block mb-2 text-sm font-medium text-gray-700">Comment</label>{{ object.comment }}</div>

      <button hx-get="/analysis/{{object.analysis.pk}}/take/create/" hx-target="#takeForm" hx-swap="outerHTML"
        class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">Edit Parameters</button>
    </div>

backend/src/analysis/templates/analysis_take_form.html
    <div class="bg-white p-4 shadow-md rounded" id="takeForm">
        <h2 class="text-lg font-semibold mb-4">Parameters for Analysis</h2>
        <!-- Parameters form elements -->
        <form id="newTakeForm" method="post" hx-post="/analysis/{{analysis}}/take/create/" hx-target="#takesSection" hx-swap="outerHTML">
            {% csrf_token %}

            <input type="hidden" name="{{ form.analysis.html_name }}" value="{{analysis }}" id="id_analysis">

            <div>
                <label class="block mb-2 text-sm font-medium text-gray-700">Window Size (default: 1024)</label>
                {{ form.window_size }}
            </div>

            <div>
                <label class="block mb-2 text-sm font-medium text-gray-700">Overlap (default: 128)</label>
                {{ form.overlap }}
            </div>

            <div>
                <label class="block mb-2 text-sm font-medium text-gray-700">FS (default: 48000)</label>
                {{ form.fs }}
            </div>

            <div>
                <label class="block mb-2 text-sm font-medium text-gray-700">Comment (optional)</label>
                {{ form.comment }}
            </div>
            <button type="submit" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">Predict
                with provided prarmeters</button>
        </form>
    </div>

backend/src/analysis/templates/analysis_take_result.html
{% if processed %}

<div class="">

  <div class="mb-4">
    <h2 class="text-xl font-semibold text-gray-800 mb-2">Analysis Results</h2>
    <div class="container mx-auto p-4">
      {% if results_status %}
      <div class="bg-white p-6 rounded shadow-md">

        <!--<div class="text-lg font-medium text-gray-900 mr-2">Result: "Wheel bearing is well"</div>-->
        <p class="text-lg">Status:
          <span class="font-bold text-{{results_color}}-500">
            {% if results_status == "good" %}
              Well
            {% else %}
              Defected
            {% endif %}
          </span>
        </p>

        <div class="flex flex-row">
          <div class="mr-2 text-sm font-semibold text-gray-500">The confidence level of the prediction:
            {{ take.analysis_result.confidence }}%</div>
          <div class="w-24 bg-white border border-gray-300  rounded-full h-4">
            <div class="bg-{{results_color}}-600 border border-{{results_color}}-600 h-4 rounded-full"
              style="width: {{ take.analysis_result.confidence }}%"></div>
          </div>

        </div>
      </div>
      {% endif %}
    </div>
  </div>

  <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
    <div class="p-4 border rounded">
      <h3 class="text-md font-semibold text-gray-800 mb-2">SOM Prediction</h3>
      <!-- Placeholder for SOM Graph -->
      <div class="h-96 bg-white rounded flex justify-center items-center">
        <!-- Dynamic content here -->
        <img class="h-96" src="{{ take.som_hitmap.url }}" alt="">
      </div>
    </div>

    <div class="p-4 border rounded">
      <h3 class="text-md font-semibold text-gray-800 mb-2">Self-organization map visualization</h3>
      <!-- Placeholder for K-Means Graph -->
      <div class="h-96 bg-white rounded flex justify-center items-center">
        <!-- Dynamic content here -->
        <img class="h-96" src="/static/SOM_map.png" alt="">
      </div>
    </div>
  </div>

  {% if results_status == "bad" %}
  <!-- Cluster Information -->
    <div class="mt-6">
      <h3 class="font-semibold">Cluster Analysis</h3>
      <p>
        The analysis of the signal has revealed patterns that are consistent with a defective wheel bearing.
      </p>
        <p>The anomaly in the signal suggests a significant deviation from the normal operational baseline, pointing towards potential mechanical failure.
        </p><p>Immediate inspection and maintenance are recommended to prevent further damage and ensure safety.
    </p>
    </div>

    <!-- Recommendations -->

    <div class="mt-6">
      <h3 class="font-semibold">Recommendations</h3>
      <p>It is advised to inspect the wheel bearing for potential damage and consider replacement if necessary.</p>
    </div>
  </div>
  {% else %}

  <!-- Cluster Information -->
    <div class="mt-6">
      <h3 class="font-semibold">Cluster Analysis</h3>
      <p>The signal analysis of the wheel bearing shows characteristics that align with a well-functioning bearing.</p>
    <p>The frequency and amplitude patterns observed are within the expected normal range, indicating no signs of wear or damage.</p>
    <p>These results suggest that the wheel bearing is operating effectively and does not currently require maintenance intervention.</p>
    <p>Continuous monitoring is advised to maintain optimal performance and early detection of any future anomalies.</p>
    </div>

    <!-- Recommendations -->

    <div class="mt-6">
      <h3 class="font-semibold">Recommendations</h3>
      <p>The wheel bearing appears to be in good condition, with no signs of damage.</p>
        <p>Regular inspections are still advised to ensure continued optimal performance.</p>
    </div>    
  {% endif %}
  {% else %}
  <div class="text-center" hx-get="{% url 'take_result' take.pk %}" hx-trigger="load delay:5s"
  hx-target="this" hx-swap="outerHTML">
    <div class="mx-auto">Proccessing not ready yet.</div>
    <div class="text-center">
      <div class="spinner mx-auto mb-4"></div>
      <h2 class="text-lg font-semibold text-gray-800">Preparing an analysis for signal with provided parameters</h2>
    </div>
  </div> 

  

  {% endif %}

backend/src/analysis/templates/create_analysis_modal.html
{% block extrahead %}
<style>
    .modal-overlay {
        background-color: rgba(0, 0, 0, 0.5);
        position: fixed;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
        display: flex;
        align-items: center;
        justify-content: center;
    }
    .modal-content {
        background-color: white;
        padding: 2rem;
        border-radius: 0.5rem;
        width: 90%;
        max-width: 600px;
    }
</style>
<script src="https://cdn.tailwindcss.com"></script>
{% endblock %}

<div id="createAnalysisModal" class="hidden fixed inset-0 bg-gray-600 bg-opacity-50 overflow-y-auto h-full w-full">
    <!-- Modal content -->
    <div class="relative top-20 mx-auto p-5 border w-5/12	 shadow-lg rounded-md bg-white">
        <div class="mt-3 text-center">
            <h3 class="text-lg leading-6 font-medium text-gray-900">Start new analysis</h3>
            <div class="mt-2" id="modal-content">

            <form method="post" enctype="multipart/form-data" class="bg-white  px-8 pt-6 pb-8 mb-4">
                {% csrf_token %}
                <div class="mb-4">
                    <label for="title" class="block text-sm font-bold text-gray-700">Title*</label>
                    {{ form.title }}
                    <p class="flex items-center gap-1 mt-2 font-sans text-sm antialiased font-normal leading-normal text-gray-700">
                        Specify title for new analysis
                      </p>
                </div>
                <div class="mb-6">
                    <label for="description" class="block text-sm font-bold text-gray-700">Description*</label>
                    {{ form.description }}
                    <p class="flex items-center gap-1 mt-2 font-sans text-sm antialiased font-normal leading-normal text-gray-700">
                        Set description for new analysis
                      </p>
                </div>
                <div class="mb-6">
                    <label for="inputSignal" class="block text-sm font-bold text-gray-700">Input Signal*</label>
                    {{ form.input_signal }}
                    <p class="flex items-center gap-1 mt-2 font-sans text-sm antialiased font-normal leading-normal text-gray-700">
                        Upload a file with wheelbearing signal. The file should be in .txt, .mat, or .csv format
                      </p>
                </div>

                <div class="flex items-center justify-end space-x-8">
                    <button type="button" onclick="toggleModal()" class="py-2 px-4 border border-transparent rounded-md shadow-sm text-sm font-medium text-white bg-red-600 hover:bg-red-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-red-500">Close</button>
                    <button type="submit" class="py-2 px-4 border border-transparent rounded-md shadow-sm text-sm font-medium text-white bg-blue-600 hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500">Submit</button>
                </div>
            </form>

            </div>
        </div>
    </div>
</div>
<script>
    function toggleModal() {
        var modal = document.getElementById("createAnalysisModal");
        modal.classList.toggle("hidden");
    }
</script>

backend/src/analysis/templates/preview_table.html
<div class="overflow-x-auto relative shadow-md sm:rounded">
    <table class="w-full text-sm text-left text-gray-500 dark:text-gray-400">
        <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
            {% if csv_data %}
                <tr>
                    {% for header in csv_data.0 %}
                        <th scope="col" class="py-3 px-6">
                            {{ header }}
                        </th>
                    {% endfor %}
                </tr>
            {% endif %}
        </thead>
        <tbody>
            {% for row in csv_data %}
                {% if forloop.counter > 1 %} <!-- Skip the header row -->
                    <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700">
                        {% for cell in row %}
                            <td class="py-4 px-6">
                                {{ cell }}
                            </td>
                        {% endfor %}
                    </tr>
                {% endif %}
            {% endfor %}
        </tbody>
    </table>
</div>

backend/src/analysis/templates/signal_analysis_list.html
{% extends "base.html" %}

{% block content %}


<div hx-get="/analysis/table/" hx-trigger="load" hx-target="this" hx-swap="outerHTML"> </div>

  {% endblock %}

backend/src/analysis/templates/signal_analysis_main.html
{% extends "base.html" %}

{% block content %}

<div class="mt-5 w-full max-w-6xl mx-auto bg-white rounded-xl shadow-xl overflow-hidden">



  <!-- Content -->

  <div class="container mx-auto p-8">

    <div class="bg-white rounded shadow-md p-5 mb-10">

      <!-- Info Section -->

      <h2 class="text-3xl font-bold text-indigo-600 mb-2">How it works?</h2>
      <div class="container mx-auto px-6 py-8">
        <div class="mb-6">
          <h2 class="text-xl font-semibold text-gray-800 mb-2">New Analysis:</h2>
          <p class="text-gray-600 mb-3">To begin, click on the "New Analysis" area in the Dashboard.</p>
          <p class="text-gray-600 mb-3">Upload a new file with signal data in CSV or TXT format.</p>
          <p class="text-gray-600 mb-3">Enter a title and a brief description for your analysis to help you identify it
            later.</p>
        </div>

        <div class="mb-6">
          <h2 class="text-xl font-semibold text-gray-800 mb-2">Signal Analysis:</h2>
          <p class="text-gray-600 mb-3">Once uploaded, you can preview the signal spectrum on the dashboard. This visual
            representation helps you understand the signal's characteristics before analysis.</p>
          <p class="text-gray-600 mb-3">Modify parameters for signal processing using the form provided. These
            parameters are crucial as they guide the unsupervised model in analyzing the data.</p>
          <p class="text-gray-600 mb-3">After setting your parameters, initiate the analysis. The app uses an
            unsupervised model to process the signal data and predicts the likelihood of a defect.</p>
        </div>

        <div class="mb-6">
          <h2 class="text-xl font-semibold text-gray-800 mb-2">Analysis Results:</h2>
          <p class="text-gray-600 mb-3">View the results of your analysis in a clear, concise format. The app displays
            the probability of a defect, along with visual graphs and charts that make interpreting the data
            straightforward.</p>
        </div>

        <div class="mb-6">
          <h2 class="text-xl font-semibold text-gray-800 mb-2">Past Records:</h2>
          <p class="text-gray-600 mb-3">Access previous analyses in the "Past Records" section.</p>
          <p class="text-gray-600 mb-3">The table view shows each analysis's date and summary. You can inspect each
            record in detail to review the findings or to compare results over time.</p>
        </div>
      </div>



      <div class="border-2 border-dashed border-indigo-400 rounded p-4 text-center">
        <button onClick="toggleModal()" class="text-indigo-500 hover:underline">
          Start New Analysis
        </button>



      </div>

    </div>

    {% include "create_analysis_modal.html" %}

    <div hx-get="/analysis/table/" hx-trigger="load" hx-target="this" hx-swap="outerHTML"> </div>


  </div>



  {% endblock %}